apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-pages
  labels:
    app: awesome
    released-by: kubectl-apply
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Document</title>
      <style>
        body {
          display: flex;
          height: 100vh;
          background: red;
        }
      </style>
    </head>
    <body>
      
      <h1>This awesome app </h1>
    </body>
    </html>
