master:
  ingress:
    enabled: true
    # paths: ["/"]
    apiVersion: "extensions/v1beta1"
    annotations:
      kubernetes.io/ingress.class: nginx
    hostName: jex.dev.vemessage.com

  installPlugins:
    - kubernetes:1.25.7
    - workflow-job:2.39
    - workflow-aggregator:2.6
    - credentials-binding:1.23
    - git:4.2.2
    - configuration-as-code:1.41
    - blueocean:1.23.2
persistence:
  enabled: true
  storageClass: aws-efs
  accessMode: "ReadWriteOnce"
  size: "1Gi"